robot:
  name: AR4
  backend: real
  degrees_of_freedom: 6
  home_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

hardware:
  port: /dev/ttyUSB0
  baudrate: 115200
  timeout: 1.0

  limits:
    joint_limits:
      neg: [-170, -42, -89, -165, -105, -155]
      pos: [170, 90, 52, 165, 105, 155]

logging:
  name: PyAr4
  log_dir: logs